version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: inspec-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: inspec
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Run init script

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inspec-app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password123
      DB_NAME: inspec
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app # Sync local files with the container
    command: ["air"]  # Ensure air is used for live reloading

volumes:
  postgres_data:
